
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
config-version: 2

seed-paths: ["data"] 
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]
